# Generated by Django 6.0.4 on 2026-04-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique ID for URL/Frontend (e.g., tech-01)', unique=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Psychology', 'Psychology'), ('Finance', 'Finance'), ('Design', 'Design')], max_length=50)),
                ('icon', models.CharField(help_text="Lucide icon name as string (e.g., 'laptop', 'brain')", max_length=50)),
                ('description', models.TextField(help_text='Short description for the card')),
                ('long_description', models.TextField(help_text='Detailed overview for the modal')),
                ('subtopics', models.JSONField(default=list, help_text="List of subtopics: ['AI', 'Web', ...]")),
                ('is_started', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.IntegerField(help_text='Order of the lesson (Day 1, Day 2...)')),
                ('time_estimate', models.CharField(default='3 min', max_length=20)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('content_data', models.JSONField(blank=True, help_text='The deep content for the LessonController', null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='api.topic')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
