# Generated by Django 6.0.4 on 2026-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lesson_content_data_savedlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='long_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='SavedTopic',
        ),
    ]
