# Generated by Django 6.0.4 on 2026-05-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_lesson_status_topic_accent_color_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='accent_color',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
    ]
